apiVersion: batch/v1
kind: Job
metadata:
  name: VAR_IMAGE_NAME
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: clients
          image: "novapokemon/client:latest"
          imagePullPolicy: Never
          command: ["sh", "-c", "./multiclient"]
          envFrom:
            - configMapRef:
                name: "services-api"
          env:
            - name: NUM_CLIENTS
              value: "VAR_CLIENT_NUMS"
            - name: REGION
              value: "VAR_REGION"
            - name: CLIENTS_TIMEOUT
              value: "VAR_CLIENTS_TIMEOUT"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /logs
              name: logs-volume
            - mountPath: /services
              name: services-volume
      volumes:
        - name: logs-volume
          hostPath:
            path: VAR_LOGS_HOST_PATH
            type: Directory
        - name: services-volume
          hostPath:
            path: VAR_SERVICES_HOST_PATH
            type: Directory
      restartPolicy: Never
      nodeSelector:
        clientsnode: "true"
  backoffLimit: 6
