apiVersion: v1
kind: PersistentVolume
metadata:
  name: VAR_CLIENT_PV_NAME
  labels:
    type: local
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "VAR_CLIENT_PV_PATH"
