apiVersion: batch/v1
kind: Job
metadata:
  name: novapokemon-tester-2-7
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: clients
          image: "novapokemon/client:latest"
          imagePullPolicy: Always
          command: ["sh", "-c", "./$multiclient"]
          envFrom:
            - configMapRef:
                name: "services-api"
          env:
            - name: NUM_CLIENTS
              value: "7"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      restartPolicy: Never
      nodeSelector:
        clientsnode: "true"
  backoffLimit: 0
