apiVersion: batch/v1
kind: Job
metadata:
  name: novapokemon-tester
spec:
  completions: 6
  parallelism: 6
  template:
    spec:
      containers:
        - name: client
          image: "novapokemon/client:latest"
          imagePullPolicy: Always
          command: ["sh", "-c", "./$executable -a"]
          envFrom:
            - configMapRef:
                name: "services-api"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      restartPolicy: Never
      nodeSelector:
        clientsnode: "true"
  backoffLimit: 4